[package]
name = "workflow-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
schema = ["dep:schemars"]

[dependencies]
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true
